#Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MemeMe' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemeMe
  #pod 'Firebase', '~> 3.5'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
end

